spring:
  application:
    name: video-hosting
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/video-hosting
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect