starter:
  uli-config:
    protocol: "http://"
    domain: "localhost:"
    port: "8080"
    pathToObtainSession: "/sessions/current"
    pathToCreateSession: "/sessions/create"
    loginParameter: "?login={log}"
  blackList:
    - "username"
    - "login"