INSERT INTO app_user (nickname, name, email) VALUES ('Alexis', 'Alex', 'named@m.m');
INSERT INTO app_user (nickname, name, email) VALUES ('Ivi', 'Ivan', 'named@m.m');
INSERT INTO app_user (nickname, name, email) VALUES ('Feofest', 'Fedor', 'named@m.m');
INSERT INTO app_user (nickname, name, email) VALUES ('Enon', 'Ekaterina', 'named@m.m');
INSERT INTO app_user (nickname, name, email) VALUES ('Olsa', 'Ola', 'named@m.m');
INSERT INTO app_user (nickname, name, email) VALUES ('Marusi', 'Masha', 'named@m.m');
INSERT INTO category (name) VALUES ('animal');
INSERT INTO category (name) VALUES ('tech');
INSERT INTO category (name) VALUES ('road');
INSERT INTO channel (name, description, author_id,main_language, category_id) VALUES ('Zoo and Animal', 'desc', '1', '1', '1');
INSERT INTO channel (name, description, author_id,main_language, category_id) VALUES ('B and M', 'desc', '2', '1', '2');
INSERT INTO channel (name, description, author_id,main_language, category_id) VALUES ('Travel', 'desc', '3', '1', '3');
INSERT INTO channel (name, description, author_id,main_language, category_id) VALUES ('Road trip', 'desc', '4', '1', '3');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('1', '1');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('2', '1');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('3', '1');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('4', '1');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('1', '2');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('3', '2');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('4', '2');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('5', '2');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('6', '2');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('1', '3');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('5', '3');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('1', '4');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('2', '4');
INSERT INTO channel_subscribers (subscribers_id, subscriptions_id) VALUES ('3', '4');
